package team4;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 개인정보관리시스템
//  @ File Name : LoginScreen.java
//  @ Date : 2021-12-16
//  @ Author : 
//
//

import java.awt.*;
import java.awt.Window;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.event.*;

public class LoginScreen extends JFrame {
    private String id;					// 입력된 아이디
    private String password;			// 입력된 비밀번호
    private boolean autochk = false;	// 자동 로그인 체크
    private LoginCtrl loginCtrlObj;		// 로그인컨트롤객체
    
    // 컴포넌트 변수
    private Container pane = getContentPane();
    private JPanel loginPanel = new JPanel(new GridLayout(3, 2));
    private JPanel contentPane;
    
    private JLabel idLabel = new JLabel("ID ");
    private JLabel pwdLabel = new JLabel("PWD ");
    private JTextField idText = new JTextField();
    private JPasswordField pwdText = new JPasswordField();
    private JCheckBox chkBtn = new JCheckBox("자동로그인");
    private JButton loginBtn = new JButton("로그인");
    private JButton joinBtn = new JButton("회원가입");
    private JButton backBtn = new JButton("<");
    
    // 생성자
    LoginScreen() {
    	super("로그인");
    	setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    	
    	setFrame();
    	setListener();
    	
    	setLocation(100,100);
    	setSize(500, 500);
    	setVisible(true);
    }
    // 컴포넌트 배치 함수
    private void setFrame() {
    	setLocationRelativeTo(null);
    	contentPane = new JPanel();
		setContentPane(contentPane);
		contentPane.setLayout(null);
		
		loginPanel.add(idLabel);
    	loginPanel.add(idText);
    	loginPanel.add(pwdLabel);
    	loginPanel.add(pwdText);
    	loginPanel.add(chkBtn);
    	loginPanel.add(joinBtn);
    	
    	backBtn.setBounds(10, 10, 40, 40);
		loginPanel.setBounds(40, 150, 400, 70);
		loginBtn.setBounds(150,300, 200, 50 );
		
		contentPane.add(loginPanel);
		contentPane.add(backBtn);
		contentPane.add(loginBtn);
    }
    // 컴포넌트의 이벤트추가 함수
    private void setListener() {	
    	loginBtn.addActionListener(new ActionListener() {
    		public void actionPerformed(ActionEvent e) {
    			id = idText.getText().trim();
    			password = pwdText.getText().trim();
    			
    			if(checkId(id) && checkPassword(password)) {
    				Login(autochk, id, password);
    			}
    		}
    	});
    	joinBtn.addActionListener(new ActionListener() {
    		public void actionPerformed(ActionEvent e) {
    			//new 회원가입Screen();
    			setVisible(false);
    		}
    	});
    	backBtn.addActionListener(new ActionListener() {
    		public void actionPerformed(ActionEvent e) {
    			new MainScreen(false);
    			setVisible(false);
    		}
    	});
    }
    private boolean checkId(String id) {
    	if(id.length() == 0) {
    		JOptionPane.showMessageDialog(null, "아이디를 입력해주세요.");
    		return false;
    	}
    	return true;
    }
    private boolean checkPassword(String pwd) {
    	if(pwd.length() == 0) {
    		JOptionPane.showMessageDialog(null, "비밀번호를 입력해주세요.");
    		return false;
    	}
    	return true;
    }
    private void Login(boolean autochk, String id, String pwd) {
    	String name;							// 사용자 이름
    	loginCtrlObj = new LoginCtrl(id, pwd);	// 입력한 id, pwd에 대한 로그인컨트롤 객체
    	
    	// 로그인컨트롤 객체-아이디,비밀번호 확인 return String(=name, 사용자 이름)
    	if((name = loginCtrlObj.checkIdPassword(autochk)) != null) {	// 로그인 성공
    		JOptionPane.showMessageDialog(null, name + " 님, 로그인되었습니다.");
    		new MainScreen(true);										// 화면 전환
    		setVisible(false);
    	}
    	else return;
    }
}
