//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 개인정보관리시스템
//  @ File Name : MemberCtrl.java
//  @ Date : 2021-12-10
//  @ Author : KAJ
//
//
package team4;

import javax.swing.JOptionPane;

/**
 * memberdb 처리관련 클래스
 * @author KAJ
 *
 */

public class MemberCtrl {
	private MemberDB db;
	
	public MemberCtrl() {
		db = new MemberDB();
	}
    /**
     * 로그인 아이디와 패스워드 검사
     * @param id
     * @param password
     * @return	검사 유효성 반환, 맞으면 true/ 틀리면 false
     */
    //checkIDPassword()
    public String check(boolean autochk, String id, String password) {
    	MemberDB info = db.getMemberInfo(id);
    	
    	if (info == null) { // 아이디가 존재하지 않을 경우
    		JOptionPane.showMessageDialog(null, "해당 아이디는 존재하지 않습니다.");
    		return null;
    	}
    	if(!info.getPassword().equals(password)) {	// 비밀번호가 틀렸을 경우
    		JOptionPane.showMessageDialog(null, "잘못된 비밀번호입니다.");
    		return null;
    	}
    	return info.getName();
    }
    
    /**
     * 회원 가입 메소드
     * @param id
     * @param password
     * @param name
     * @param birthdate
     * @param phoneNumber
     * @param address
     */
    //InsertMemberInfo()
    public void join(String id, String password, String name, String birthdate, String phoneNumber, String address) {
    	if(db.insertMemberInfo(id, password, name, birthdate, phoneNumber, address)) {
    		JOptionPane.showMessageDialog(null, "회원가입되었습니다.");
    	}
    	else {
    		JOptionPane.showMessageDialog(null, "회원가입에 실패하였습니다.");
    	}
    }
    
}
