//
//
//  Generated by StarUML(tm) Java Add-In

// 멤버 계정 추가/조회
//
//  @ Project : 개인정보관리시스템
//  @ File Name : MemberDB.java
//  @ Date : 2021-12-10
//  @ Author : KAJ
//
//
package team4;
//import account.AccountCtrl;
import java.sql.*;

/**
 * 
 * @since 2021.12.10
 */

public class MemberDB {
	private String id;				// 아이디
	private String password;		// 패스워드
	private String name;			// 이름
	private String birthdate;		// 생일
	private String phoneNumber;		// 전화번호
	private String address;			// 주소
	private DBConnection dbcon;	// MemberDB 데이터베이스 연결
	
	/**
	 * memberdb를 다룰 객체 생성
	 * memberdb 데이터베이스 연결
	 */
	public MemberDB() {
		dbcon = new DBConnection();
	}
	public MemberDB(String id, String pwd, String name, String birthdate, String phoneNumber, String address) {
		this.id = id;
		this.password = pwd;
		this.name = name;
		this.birthdate = birthdate;
		this.phoneNumber = phoneNumber;
		this.address = address;
	}
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getBirthdate() {
		return birthdate;
	}
	public void setBirthdate(String birthdate) {
		this.birthdate = birthdate;
	}
	public String getPhoneNumber() {
		return phoneNumber;
	}
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	/**
	 * memberdb에 새로운 회원 추가
	 * memberdb에 연결
	 * 새로운 회원 memberdb에 삽입
	 * 
	 * @param id			아이디
	 * @param password		패스워드
	 * @param name			이름
	 * @param birthdate		생일
	 * @param phoneNumber	전화번호
	 * @param address		주소
	 */
	public boolean insertMemberInfo(String id, String password, String name, String birthdate, String phoneNumber, String address) {
		Statement stmt = null;
		
		try {
			// 데이터베이스 연결
			stmt = dbcon.db_connect();
			
			// memberdb에 새로운 회원 삽입
			stmt.executeUpdate("insert into memberdb values ('"
					+ id + "', '"
					+ password + "', '"
					+ name + "', '"
					+ birthdate + "', '"
					+ phoneNumber + "', '"
					+ address + "' );");
			dbcon.db_close();
			return true;
		} catch (SQLException ex) {
			System.out.println("새로운 회원 삽입 SQL 에러");
		}
		return false;
	}    
    /**
     * 로그인 아이디와 패스워드가 맞는 지 검사
     * @param id			아이디
     * @param password		패스워드
     * @return				패스워드 일치 여부 반환(일치: MemberDB, 불일치: null)
     */
    public MemberDB getMemberInfo(String id) {//id를 통한 정보 불러오기 성공
    	Statement stmt;
    	String pwd = null;
    	String name = null;
    	String birthdate = null;		
    	String phoneNumber = null;		
    	String address = null;	
    	try {
    		// 데이터베이스 연결
    		stmt = dbcon.db_connect();
    		// 로그인 아이디에 맞는 패스워드인지 검사
    		String sql = "select * from memberdb where id='" + id+"'";
    		ResultSet rs = stmt.executeQuery(sql);

    		while (rs.next()) {
    			pwd = rs.getString(2);
    			name = rs.getString(3);
    			birthdate = rs.getString(4);
    			phoneNumber = rs.getString(5);
    			address = rs.getString(6);
    			return new MemberDB(id, pwd, name, birthdate, phoneNumber, address);
    		}
    		dbcon.db_close();
    	} catch (SQLException ex) {
    		ex.printStackTrace();
    		System.out.println("아이디 패스워드 검사 SQL 에러");
    		return null;
    	}
    	System.out.println("no data");
    	return null;
    }
}
	
