//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 개인정보관리시스템
//  @ File Name : MemberCtrl.java
//  @ Date : 2021-12-10
//  @ Author : KAJ
//
//
package member;

import javax.swing.JOptionPane;

/***********************************************************
 * MemberCtrl : memberdb 처리관련 클래스
/***********************************************************/
public class MemberCtrl {
	private MemberDB db;			// 멤버디비 객체
	
	/***********************************************************
     * 생성자 : 멤버디비 객체 생성
    /***********************************************************/
	public MemberCtrl() {
		db = new MemberDB();		// 멤버디비 객체 생성
	}

	/***********************************************************
     * String check() : 아이디, 비밀번호의 유효성 체크
	 * @param boolean autochk : 자동로그인 체크 유무
	 * @param String id : 입력된 아이디 
	 * @param String password : 입력된 비밀번호
	 * @return	검사 유효성 반환, 맞으면 사용자이름/ 틀리면 null
    /***********************************************************/
    public String check(boolean autochk, String id, String password) {
    	// 입력된 아이디와 일치하는 계정정보 검색하여 info에 저장
    	MemberDB info = db.getMemberInfo(id);
    	
    	// 아이디가 존재하지 않을 경우
    	if (info == null) { 
    		JOptionPane.showMessageDialog(null, "해당 아이디는 존재하지 않습니다.");
    		return null;
    	}
    	// 비밀번호가 틀렸을 경우
    	if(!info.getPassword().equals(password)) {	
    		JOptionPane.showMessageDialog(null, "잘못된 비밀번호입니다.");
    		return null;
    	}
    	// 입력한 아이디와 비밀번호가 유효하면 해당 계정의 사용자이름을 리턴
    	return info.getName();
    }
    
    /***********************************************************
     * void join() : 회원가입
	 * @param String id : 아이디
	 * @param String password : 비밀번호 
	 * @param String name : 이름
	 * @param String birthdate : 주민번호 
	 * @param String phoneNumber : 전화번호
	 * @param String address : 주소
    /***********************************************************/
    public void join(String id, String password, String name, String birthdate, String phoneNumber, String address) {
    	// 파라미터의 정보를 이용하여 데이터베이스에 정보 입력
    	if(db.insertMemberInfo(id, password, name, birthdate, phoneNumber, address)) {
    		JOptionPane.showMessageDialog(null, "회원가입되었습니다.");
    	}
    	else {
    		JOptionPane.showMessageDialog(null, "회원가입에 실패하였습니다.");
    	}
    }
    
}
