//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 개인정보관리시스템
//  @ File Name : AccountCtrl.java
//  @ Date : 2021-12-10
//  @ Author : KAJ
//
//

package account;

public class AccountCtrl {
	public int accountId;	// 각 데이터행 고유 번호 PK
	public String id;		// 로그인 아이디 FK
	public String site;		// 사이트 이름
	public String siteId;	// 사이트 아이디
	public String IP;		// 접속 아이피
    public String userInfoList;	// 유저의 정보
    AccountDB account;
    
    String[][] information2 = new String[10][3];
    
    /**
     * 데이터베이스를 다룰 DB 객체 생성
     * @param accountId		계정아이디
     * @param id			아이디
     */
    public AccountCtrl(String id) {
    	account = new AccountDB();
    	this.id = id;
    }
    
    public AccountCtrl() {
    	account = new AccountDB();
    }
    
    public String[][] AccountInquiry() {			// 계정 조회
    	information2 = account.InfoInquiry(this.id);	// accountDB의 InfoInquiry 함수에서 계정정보를 받아
    	return information2;							// 리턴한다.
    }
    
    public void WithdrawlProgressInquiry() {	// 탈퇴 진행 내역 조회
    }
    
    public void WithdrawalInquiry() {			// 탈퇴 완료 내역 조회
    }
    
    public void RejectedInquiry() {				// 반려 내역 조회
    }
    
    public void requestAccountWithdrawal(String account) {	// 계정 탈퇴 요청
    }
}
