//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 개인정보관리시스템
//  @ File Name : AccountDB.java
//  @ Date : 2021-12-11
//  @ Author : KAJ
//
//
package account;

import team4.DBConnection;
import java.sql.ResultSet;
import java.sql.SQLException;


/**
 * 계정 관리와 관련된 정보들을 저장하는 db
 * @author A
 *
 */
public class AccountDB {
	public int accountId;	// 각 데이터 행 고유번호 PK
	public String id;		// 로그인 아이디 FK
    public String site;		// 사이트 이름	
    public String siteId;	// 사이트 아이디
    public String IP;		// 아이피
    
    DBConnection dbcon;
    
    public AccountDB() {
    	dbcon = new DBConnection();
    }
    
    /**
     * 
     * @param accountId		계정아이디 P.K
     * @param id			로그인 아이디 F.K
     * @param site			사이트명
     * @param siteId		사이트 아이디
     * @param IP			아이피
     */
    
    public void insertAccount(int accountId, String id, String site, String siteId, String IP) {		// 계정 추가
    	java.sql.Statement stmt;
    	
    	stmt = dbcon.db_connect();
    	
    	try {
    		stmt.executeUpdate("insert into accountdb values (" 
    				+ accountId + ", '" 
    				+ id + "', '"
    				+ site + "', '"
    				+ siteId + "', '"
    				+ IP + "');");
    		dbcon.db_close();
    	} catch (SQLException ex) {
    		System.out.println("SQL 에러");
    	}
    }
    
    
    public String[][] InfoInquiry(String id) {		// 현재 로그인된 계정의 아이디를 가지고 데이터베이스 내에 있는 정보들을 불러와 infomation2 변수에 대입해 리턴한다.
   
    	String[][] information2 = new String[10][3];	
    	
    	java.sql.Statement stmt;
    	stmt = dbcon.db_connect();
    	
    	try {
    		ResultSet rs = stmt.executeQuery("select * from information");		// information 데이터베이스의 모든 데이터들을 불러온다.
    		
    		int k = 0;
    		while (rs.next()) {	
    			if(id.equals(rs.getString(2).trim())) {		// 현재 로그인된 아이디와 데이터베이스의 FK 아이디와 비교하여 같다면
    				for(int i = 1, j = 0; i < 6; i++) {		// 열의 갯수만큼 for문을 실행시키는데
    					if(i >= 3) {						// GUI에 개시할 정보는 사이트명, 사이트 아이디, 아이피 이므로
    						information2[k][j] = rs.getString(i);		// 3열~ 5열의 데이터를 대입한다.
    						j++;
    					}				
        			}
    				k++;									// infomation2의 다음 행으로 넘어간다.
    			}
    		}
    	} catch (SQLException ex) {
    		System.out.println("아이디에 해당되는 사이트명, 사이트아이디, IP 얻기 SQL 에러");
    	}
 
    	return information2;
    }
    
}

